### ISSUE TITLE
new onStart is called before component has owner

### ISSUE THREAD

**Issue by markknol** [aduros/flambe#284]
I have issues with the new onStart getting called too early, when it does not have an owner yet. 
If you dynamically add new Entities in the game, it sometimes gives an error that _"Cannot read property 'getComponent' of null "_ inside the onStart function. I'm not sure which construction this behavior triggers exactly (must be a ordering thing, while in update loop and stuff gets added inbetween), the fix seems relative simple.

I would suggest to change _MainLoop.hx:99-112_ to this

```
        // Update components
        var p = entity.firstComponent;
        while (p != null) {
            var next = p.next;
            if (entity.parent != null)
            {
                if (!p._flags.contains(Component.STARTED)) {
                    p._flags = p._flags.add(Component.STARTED);
                    p.onStart();
                }
                p.onUpdate(dt);
            }
            p = next;
        }
```

If the owner has a parent, it could be considered as started. In this case onStart only gets called when the component has an owner that is on the displaylist. the onUpdate also got an update in that same case, that's fixed too.

What do you think?

**Comment by Misiur** [comment]
For future visitors: You need to add `using flambe.util.BitSets;` on top of file in which you use `_flags.add`, as `_flags` is an integer, and `BitSets` are a [static extension](http://haxe.org/manual/lf-static-extension.html)
