### ISSUE TITLE
lots of files in assetfolder slows down build

### ISSUE THREAD

**Issue by markknol** [aduros/flambe#298]
If you have lots of files in assetfolders, building becomes quite slow.
This is a temp manual fix that disables the copy-pasting, but should be fixed in the buildscript in ideal cases.

`C:\Users\%username%\AppData\Roaming\npm\node_modules\flambe\index.js`
_line number 157_

```
var prepareAssets = function (dest) {
        /*
        wrench.rmdirSyncRecursive(dest);

        // TODO(bruno): Filter out certain formats based on the platform
        return copyDirs(assetPaths, dest)
        .then(function () {
            return ["--macro", "flambe.platform.ManifestBuilder.use(\""+dest+"\")"];
        });
        */
        return ["--macro", "flambe.platform.ManifestBuilder.use(\""+dest+"\")"];
    };
```

**Comment by markknol** [comment]
Is there a fix available to make the asset copying faster?

**Comment by markknol** [comment]
It not only slows down the build, but also the asset server. We have a project with 350mb of assets (per level different backgrounds and icons so not everything is loaded at same time). It seems the more assets we add, the more memory it consumes.

To illustrate, I'm now at 100% full force consumption. that means I cannot do anything while keeping the flambe server open.
![upload 5](https://cloud.githubusercontent.com/assets/576184/5815141/1fe63ea6-a093-11e4-90d7-a0e4ce68955d.png)

I now try to use apache server instead of flambe server. 
We already disabled the copy-pasting as mentioned in the first comment, but I created an own asset sync script too, because if we enable it takes 5 minutes to complete the build.

I hope you understand this does feels not ok, I hope you can help provide a solution for this.

**Comment by aduros** [comment]
Thanks Mark, I'm taking a look. The CPU usage seems to suggest it's not simply IO-bound. If possible, please send me a zip of your assets folder (will remain private) so I have a real world test case?

**Comment by markknol** [comment]
Ok cool, I've send you the files, thanks for looking into this!

**Comment by markknol** [comment]
Any news on this? Maybe an interesting thingy, I use fastcopy to sync the asset folders.

_copy-assets-to-build.bat_
`tools\fastcopy\fastcopy.exe /auto_close /cmd=sync "assets\" /to="build\web\assets" `

I use this in my pre-build command in FlashDevelop.
This syncs the directories within seconds, since it only alters what actually changed in between. This only works on windows.

**Comment by aduros** [comment]
I used the archive you sent me and put it in a project, and it takes under 5 seconds to build. I tried it on another low spec machine with no SSD (mac mini), and it took 10 seconds.

That can be improved, but it shouldn't be taking 5 minutes... could there be something else going on?

**Comment by markknol** [comment]
About the asset copying:
Did you also tests on Windows? I'm sure it is related to to the copy-part, when I disable it, it builds fast, within 5 seconds. Colleagues experience the same issue, I also notice this at my home laptop.

About the flambe server;
Did you notice that a lot of memory is used?

Btw I have 16GB of ram, and i5 processor, but indeed no SSD.
