### ISSUE TITLE
Property "get_height" already defined in this object literal.

### ISSUE THREAD

**Issue by sonygod** [aduros/flambe#345]
build\.cache\html.unminified.js:2321: ERROR - Parse error. Property "get_height" already defined in this object literal.
	,__properties__: {get_height:"get_height",get_width:"get_width",get_height:"get_height",get_width:"get_width"}

I try to build my test project to html target ,and get that error (debug mode is ok)

how to fixed that ?

**Comment by sonygod** [comment]
after restart computer and recompile ,it is ok ,auto fixed!

**Comment by markknol** [comment]
It can also be fixed by killing the haxe.exe task from task manager. I also have this sometimes, seems a nasty thing in the Haxe compiler.
