### ISSUE TITLE
Could not compile project to html5

### ISSUE THREAD

**Issue by yuigoto** [aduros/flambe#346]
Hi! I'm studying haxe and I wanted to try some game/app engines to see which one I feel more comfortable with.

Just installed flambe and all its dependencies, but I came upon these errors, when building a blank project while targeting html5 (as described in the install guide):

<code>
Building: build/web
haxe -main urgame.Main -lib flambe -cp src -dce full -debug --no-opt --no-inline -D html -D js-es5 -
D js-flatten --macro flambe.platform.ManifestBuilder.use("build/web/assets") -D source-map-content -
js build/web/targets/main-html.js
C:\Aplicativos\Desenvolvimento\HaxeToolkit\haxe\lib/flambe/4,1,0/flambe/platform/html/CanvasTextureRoot.hx:44: characters 28-32 : Array<Int> should be haxe.io.BytesData
C:\Aplicativos\Desenvolvimento\HaxeToolkit\haxe\lib/flambe/4,1,0/flambe/platform/html/CanvasTextureRoot.hx:44: characters 28-32 : Array<Int> should be js.html.ArrayBuffer
C:\Aplicativos\Desenvolvimento\HaxeToolkit\haxe\lib/flambe/4,1,0/flambe/platform/html/CanvasTextureRoot.hx:44: characters 28-32 : For function argument 'b'
C:\Aplicativos\Desenvolvimento\HaxeToolkit\haxe\lib/flambe/4,1,0/flambe/platform/html/CanvasTextureRoot.hx:39: lines 39-45 : Missing return haxe.io.Bytes
C:\Aplicativos\Desenvolvimento\HaxeToolkit\haxe\lib/flambe/4,1,0/flambe/platform/html/HtmlAssetPackLoader.hx:364: characters 16-38 : String should be js.html.XMLHttpRequestResponseType
C:\Aplicativos\Desenvolvimento\HaxeToolkit\haxe\lib/flambe/4,1,0/flambe/platform/html/HtmlAssetPackLoader.hx:367: characters 12-37 : String should be js.html.XMLHttpRequestResponseType
C:\Aplicativos\Desenvolvimento\HaxeToolkit\haxe\lib/flambe/4,1,0/flambe/platform/html/HtmlAssetPackLoader.hx:368: characters 16-42 : String should be js.html.XMLHttpRequestResponseType
C:\Aplicativos\Desenvolvimento\HaxeToolkit\haxe\lib/flambe/4,1,0/flambe/platform/html/HtmlAssetPackLoader.hx:205: characters 12-43 : String should be js.html.XMLHttpRequestResponseType
C:\Aplicativos\Desenvolvimento\HaxeToolkit\haxe\lib/flambe/4,1,0/flambe/platform/html/HtmlExternal.hx:37: characters 42-48 : js.html.Window should be haxe.Function
C:\Aplicativos\Desenvolvimento\HaxeToolkit\haxe\lib/flambe/4,1,0/flambe/platform/html/HtmlExternal.hx:37: characters 42-48 : For function argument 'func'
C:\Aplicativos\Desenvolvimento\HaxeToolkit\haxe\lib/flambe/4,1,0/flambe/platform/html/HtmlExternal.hx:25: lines 25-38 : Missing return Dynamic
</code>

Maybe I didn't install it properly? :sweat_smile: Anyone knows what's happening here?

Thanks. :smile:

**Comment by markknol** [comment]
Well, you have installed the newest Haxe version (3.2)

To be compatible with Haxe 3.2, apply this patch: https://github.com/aduros/flambe/commit/ec084011873cf16635f4e2a77cc0d2dc6c58625d 
It is already in this repository, but not released (yet).

**Comment by yuigoto** [comment]
Oh, thanks for the answer! :smile: And yup, just updated Haxe and all other libraries.

Updated the files, I also had to update "HtmlExternal.hx" besides the ones you've mentioned. It worked like a charm!

Time to study Haxe a bit harder now! :sweat_smile:

Thanks again!

**Comment by markknol** [comment]
Make sure you read the flambe guide https://github.com/markknol/flambe-guide/wiki

**Comment by yuigoto** [comment]
Already diggin' through! :sweat_drops:

Thanks. :wink:

**Comment by azrafe7** [comment]
What's the fix for HtmlExternal.hx?

**Comment by azrafe7** [comment]
nvm, found it! https://github.com/aduros/flambe/commit/c2f3e025186aa776e21ea98c9f0e59b4e15c8ad7

**Comment by ambry11** [comment]
Hi I'm very new to this flambe stuff and I having the same problem with yuigoto.
I just wanna ask how to apply the fix that markknol stated, I dont know how to apply the patch.
I've watched the video tutorial about the installation and I did everything from that video.
Please help me how to apply the patch into flambe.
Thanks!
