### ISSUE TITLE
Scroll listener not working under chrome due to a browser bug

### ISSUE THREAD

**Issue by Misiur** [aduros/flambe#362]
I thought this was a flambe problem, but I found out it's not. Due to `HtmlPlatform.hx` using `MouseEvent#timeStamp` as a debounce method this bug causes `mousewheel` not to fire at all in chrome. I'd suggest keeping this issue open for other people, and for tracking the chrome bug. I hope they won't close it as irrelevant, otherwise flambe will have to adjust it's code accordingly. 
https://code.google.com/p/chromium/issues/detail?id=583000

**Comment by Misiur** [comment]
Problem fixed in chrome

**Comment by markknol** [comment]
Thanks for mentioning anyway :smile:
