### ISSUE TITLE
Signal priority

### ISSUE THREAD

**Issue by Misiur** [aduros/flambe#363]
Is there a way to make listener moved to the top of listener stack? Some kind of priority queue? I need to stop propagation on certain event, however it's dynamically added, and lands as one of the last to be executed.

**Comment by markknol** [comment]
Every connect function has a prioritize parameter. It will execute faster than normal signal connections.

**Comment by Misiur** [comment]
Missed that, thanks!

**Comment by markknol** [comment]
No problem!
