### ISSUE TITLE
A black rectangle in HTML5 & Chrome

### ISSUE THREAD

**Issue by markosman** [aduros/flambe#372]
Whenever I try to load a program that I built in HTML5 using Chrome I see a black rectangle in the left side of the screen (see images) next to the program. It doesn't happen on Firefox and Internet explorer, only on Chrome. Moreover, Flash works fine in Chrome.

For some reason, the Flambe demos work fine in HTML5 & Chrome. For example, here is an image of [the browser demo](https://aduros.com/flambe/demos/browser/?flambe=html) (that I didn't build):

![flambe browser](https://s16.postimg.org/jubniww91/flambe_Browser.png)

And this is the browser demo after I built it in HTML5:

![flambe error](https://s15.postimg.org/9px0pmscb/flambe_Error.png)

These are the versions that I use:

- Haxe 3.1.3
- air3 0.0.1
- flambe 4.1.0
- format 3.1.2
- hxsl 2.0.5

Does anyone know what is going on here?

**Comment by markknol** [comment]
Maybe there is something wrong with your html in which it runs?

**Comment by markknol** [comment]
The default index page isn't designed to be used in production. 

Also, it looks like your browser is zoomed in (I see an icon at right side of your adressbar).

**Comment by markosman** [comment]
You are right, thanks !
